# Generated by Django 3.1.5 on 2021-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20210417_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sum_4',
        ),
        migrations.AddField(
            model_name='profile',
            name='tech_skills',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity_1',
            field=models.CharField(default='', max_length=300),
        ),
    ]
