# Generated by Django 3.1.5 on 2021-05-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_auto_20210515_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='construction_sum_1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
