# Generated by Django 3.1.5 on 2021-05-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_profile_construction_sum_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='security_sum_1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
