# Generated by Django 3.1.5 on 2021-05-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0006_profile_security_sum_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='work_1b',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_1d',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_1f',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_1g',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_1h',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_2b',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_2d',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_2f',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_2g',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_2h',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_3b',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_3d',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_3f',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_3g',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_3h',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_4b',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_4d',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_4f',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_4g',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_4h',
        ),
    ]
